# Generated by Django 4.2.4 on 2023-12-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='project_description',
            new_name='projComponents',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='date_needed_by',
            new_name='projDate',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='specific_components',
            new_name='projDescription',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='project_name',
            new_name='projName',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='style_color_preferences',
            new_name='projStyle',
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
