# Generated by Django 4.2.4 on 2023-12-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_project_description_form_projcomponents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='projStatus',
            field=models.CharField(choices=[('Awaiting Review', 'Awaiting Review'), ('Needs Client Review', 'Needs Client Review'), ('Project Finished', 'Project Finished')], default='Awaiting Review', max_length=255),
        ),
    ]
